const L=[['index.html','Início'],['about.html','Sobre'],['services.html','Serviços'],['projects.html','Projetos'],['bup.html','Bup'],['contact.html','Contato']],here=location.pathname.split('/').pop()||'index.html';
document.body.insertAdjacentHTML('afterbegin','<div class="grid"></div><div class="blob" style="width:420px;height:420px;background:#ff9ad0;left:-100px;top:-80px"></div><div class="blob" style="width:380px;height:380px;background:#8fb4ff;right:-80px;bottom:5%;animation-delay:-5s"></div><div class="blob" style="width:340px;height:340px;background:#ffb46b;left:40%;bottom:-120px;animation-delay:-9s"></div><nav class="pill">'+L.map(l=>`<a href="${l[0]}" class="${l[0]==here?'on':''}">${l[1]}</a>`).join('')+'</nav>');
document.body.insertAdjacentHTML('beforeend','<footer><div class="fw"><div><a href="https://ticord.website" target="_blank" rel="noopener" aria-label="Grupo Ticord"><img src="ticord.png" alt="Grupo Ticord"></a><p>Bots, sites e automações. Grupo Ticord.</p></div><ul>'+L.map(l=>`<li><a href="${l[0]}">${l[1]}</a></li>`).join('')+'<li><a href="faq.html">Perguntas frequentes</a></li><li><a href="terms.html">Termos de Serviço</a></li><li><a href="privacy.html">Política de Privacidade</a></li></ul><div><a class="fc" href="https://wa.me/5519999894031">(19) 99989-4031</a><p><a class="fc" href="mailto:helpticord@gmail.com">helpticord@gmail.com</a></p></div></div><small>© 2026 Todos os direitos reservados.</small></footer>');
if(matchMedia('(pointer:fine)').matches){
document.body.classList.add('hc');const d=document.createElement('div');d.className='dot';document.body.append(d);let x=-50,y=-50,s=1;const draw=()=>{d.style.transform=`translate(${x}px,${y}px) scale(${s})`};
addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;d.classList.add('on');draw();const r=document.documentElement.style;r.setProperty('--mx',(x-innerWidth/2)/35+'px');r.setProperty('--my',(y-innerHeight/2)/35+'px')});
document.addEventListener('mouseover',e=>{s=e.target.closest('a,button,summary')?1.8:1;draw()});
if(!matchMedia('(prefers-reduced-motion:reduce)').matches){let t=scrollY,c=scrollY;
addEventListener('wheel',e=>{if(e.target.closest('.scroll'))return;e.preventDefault();t=Math.max(0,Math.min(t+e.deltaY*.4,document.documentElement.scrollHeight-innerHeight))},{passive:false});
addEventListener('scroll',()=>{if(Math.abs(scrollY-c)>60)t=c=scrollY});
(function f(){c+=(t-c)*.06;if(Math.abs(t-c)>.2)scrollTo(0,c);requestAnimationFrame(f)})()}}
